# Generated by Django 5.2.8 on 2025-11-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('telecaller', 'Telecaller'), ('teamlead', 'Team Lead'), ('groundstaff', 'Ground Staff')], max_length=20)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
