# Generated by Django 5.2.8 on 2025-11-15 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0002_createuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='admin_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kg_app.admin_user_model'),
        ),
    ]
