# Generated by Django 5.1.3 on 2025-11-17 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0003_createuser_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admin_user_model',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='Create_task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('adreement_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=50)),
                ('tc_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('count_of_cases', models.CharField(max_length=20)),
                ('old_or_new', models.CharField(max_length=20)),
                ('bucket', models.CharField(max_length=15)),
                ('mode', models.CharField(max_length=30)),
                ('npa_status', models.CharField(max_length=50)),
                ('pos_amount', models.CharField(max_length=50)),
                ('total_charges', models.CharField(max_length=30)),
                ('bcc_pending', models.CharField(max_length=20)),
                ('penal_pending', models.CharField(max_length=20)),
                ('emi_amount', models.CharField(max_length=30)),
                ('emi_due_amount', models.CharField(max_length=30)),
                ('recipt_amount', models.CharField(max_length=30)),
                ('recipt_date', models.CharField(max_length=20)),
                ('disbursement_amount', models.CharField(max_length=30)),
                ('loan_amount', models.CharField(max_length=30)),
                ('disbursement_date', models.CharField(max_length=20)),
                ('emi_start_date', models.CharField(max_length=20)),
                ('emi_end_date', models.CharField(max_length=20)),
                ('emi_cycle_date', models.CharField(max_length=20)),
                ('make', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=50)),
                ('fe_name', models.CharField(max_length=50)),
                ('fe_mobile_number', models.CharField(max_length=10)),
                ('customer_mobile_number', models.CharField(max_length=10)),
                ('pin_code', models.CharField(max_length=6)),
                ('customer_address', models.CharField(max_length=500)),
                ('customer_office_address', models.CharField(max_length=500)),
                ('reference_details', models.CharField(max_length=500)),
                ('collection_manager_name', models.CharField(max_length=100)),
                ('finance_company_name', models.CharField(max_length=200)),
                ('admin_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kg_app.admin_user_model')),
            ],
        ),
    ]
