# Generated by Django 5.1.3 on 2025-11-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0004_createuser_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createuser',
            name='address',
        ),
    ]
