# Generated by Django 5.1.3 on 2025-11-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0005_remove_createuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_user_model',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
