# Generated by Django 5.1.3 on 2025-11-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0006_alter_admin_user_model_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
