# Generated by Django 5.1.3 on 2025-11-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0007_alter_createuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
