# Generated by Django 5.1.3 on 2025-11-17 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0008_createuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_task',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kg_app.admin_user_model'),
        ),
    ]
