# Generated by Django 5.1.3 on 2025-11-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0009_alter_create_task_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createuser',
            name='address',
        ),
    ]
