# Generated by Django 5.1.3 on 2025-11-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0010_remove_createuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
