# Generated by Django 5.1.3 on 2025-11-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0011_createuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_task',
            name='employer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='manufacturer_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='registration_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='vehicle_age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
