# Generated by Django 5.1.3 on 2025-11-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0012_create_task_employer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_task',
            old_name='adreement_id',
            new_name='aggrement_id',
        ),
    ]
