# Generated by Django 5.2.8 on 2025-11-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0013_rename_adreement_id_create_task_aggrement_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TcLogin',
            fields=[
                ('tc_login_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
