# Generated by Django 5.1.3 on 2025-11-29 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0016_gslogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_task',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='task_update',
            fields=[
                ('task_update_id', models.AutoField(primary_key=True, serialize=False)),
                ('agreement_id', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('new_mobile_number', models.CharField(max_length=15)),
                ('projection', models.CharField(max_length=100)),
                ('projection_date', models.CharField(max_length=20)),
                ('projection_amount', models.CharField(max_length=30)),
                ('customer_remark', models.CharField(max_length=500)),
                ('reference_remark', models.CharField(max_length=500)),
                ('need_group_visit', models.CharField(max_length=10)),
                ('visit_projection', models.CharField(max_length=100)),
                ('visit_status', models.CharField(max_length=20)),
                ('customer_available', models.CharField(max_length=20)),
                ('vehicle_available', models.CharField(max_length=10)),
                ('third_party_status', models.CharField(max_length=10)),
                ('third_party_details', models.CharField(max_length=500)),
                ('new_update_address', models.CharField(max_length=500)),
                ('location_image', models.ImageField(blank=True, null=True, upload_to='location_image/')),
                ('location_status', models.CharField(max_length=20)),
                ('payment_info', models.CharField(max_length=500)),
                ('payment_mode', models.CharField(max_length=50)),
                ('payment_amount', models.CharField(max_length=30)),
                ('payment_date', models.CharField(max_length=20)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kg_app.admin_user_model')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kg_app.create_task')),
            ],
        ),
    ]
