# Generated by Django 5.1.3 on 2025-11-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0017_create_task_category_task_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_update',
            old_name='projection_amount',
            new_name='promise_amount',
        ),
        migrations.RenameField(
            model_name='task_update',
            old_name='projection_date',
            new_name='promise_date',
        ),
    ]
