# Generated by Django 5.1.3 on 2025-11-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0018_rename_projection_amount_task_update_promise_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_update',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
