# Generated by Django 5.2.9 on 2025-12-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0019_task_update_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_update',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
