# Generated by Django 5.2.9 on 2025-12-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0020_task_update_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_update',
            name='payment_date',
            field=models.DateTimeField(max_length=20),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='promise_date',
            field=models.DateTimeField(max_length=20),
        ),
    ]
