# Generated by Django 5.2.9 on 2025-12-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0021_alter_task_update_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_task',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
