# Generated by Django 5.2.9 on 2025-12-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0022_create_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_task',
            name='new_mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='projection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
