# Generated by Django 5.2.9 on 2025-12-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0023_create_task_new_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_task',
            name='api_image_status',
            field=models.CharField(blank=True, default='No', max_length=20, null=True),
        ),
    ]
