# Generated by Django 5.2.9 on 2025-12-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0024_create_task_api_image_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_update',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
