# Generated by Django 5.2.9 on 2025-12-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0025_task_update_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_update',
            name='document',
        ),
        migrations.AddField(
            model_name='task_update',
            name='document_image',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
