# Generated by Django 5.2.9 on 2025-12-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0026_remove_task_update_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_update',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='customer_available',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='customer_remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='location_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='need_group_visit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='new_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='new_update_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='payment_amount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='payment_date',
            field=models.DateTimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='payment_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='promise_amount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='promise_date',
            field=models.DateTimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='reference_remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='third_party_details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='third_party_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='vehicle_available',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='visit_projection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='visit_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
