# Generated by Django 5.2.9 on 2025-12-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0027_alter_task_update_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_update',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task_update',
            name='promise_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
