# Generated by Django 5.2.9 on 2025-12-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0028_alter_task_update_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_update',
            name='payment_info',
        ),
        migrations.AddField(
            model_name='create_task',
            name='update_customer_available',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='update_customer_remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='update_location_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='update_need_group_visit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='update_new_update_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='update_payment_amount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='update_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='update_payment_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='update_promise_amount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='update_promise_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='update_recipt_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='update_reference_remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='update_third_party_details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='update_third_party_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='update_vehicle_available',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='update_visit_projection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task_update',
            name='recipt_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
