# Generated by Django 5.2.9 on 2025-12-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0029_remove_task_update_payment_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_task',
            name='update_new_update_address',
        ),
        migrations.AddField(
            model_name='create_task',
            name='update_new_address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
