# Generated by Django 5.2.9 on 2025-12-25 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0030_remove_create_task_update_new_update_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gslogin',
            name='user_id',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='kg_app.createuser'),
        ),
        migrations.AddField(
            model_name='tclogin',
            name='user_id',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='kg_app.createuser'),
        ),
        migrations.AddField(
            model_name='tllogin',
            name='user_id',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='kg_app.createuser'),
        ),
        migrations.AlterField(
            model_name='gslogin',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gslogin',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tllogin',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tllogin',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),
    ]
