# Generated by Django 5.2.9 on 2025-12-25 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0032_alter_gslogin_user_id_alter_tclogin_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gslogin',
            name='user_id',
            field=models.ForeignKey(blank=True, default=11, null=True, on_delete=django.db.models.deletion.CASCADE, to='kg_app.createuser'),
        ),
        migrations.AlterField(
            model_name='tclogin',
            name='user_id',
            field=models.ForeignKey(blank=True, default=11, null=True, on_delete=django.db.models.deletion.CASCADE, to='kg_app.createuser'),
        ),
        migrations.AlterField(
            model_name='tllogin',
            name='user_id',
            field=models.ForeignKey(blank=True, default=11, null=True, on_delete=django.db.models.deletion.CASCADE, to='kg_app.createuser'),
        ),
    ]
