# Generated by Django 5.2.9 on 2025-12-28 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0034_alter_tclogin_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gslogin',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kg_app.createuser'),
        ),
        migrations.AlterField(
            model_name='tllogin',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kg_app.createuser'),
        ),
    ]
