# Generated by Django 5.2.9 on 2025-12-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0035_alter_gslogin_user_id_alter_tllogin_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_user_model',
            name='login_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admin_user_model',
            name='user_count',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='create_task',
            name='fe_userName',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='tc_userName',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
