# Generated by Django 5.2.9 on 2026-01-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0036_admin_user_model_login_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_user_model',
            name='active_session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admin_user_model',
            name='last_login_device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='createuser',
            name='active_session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='createuser',
            name='last_login_device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
