# Generated by Django 5.2.9 on 2026-01-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0037_admin_user_model_active_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_task',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task_update',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task_update',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
