# Generated by Django 5.2.9 on 2026-01-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0038_create_task_latitude_create_task_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='isMobile_login',
            field=models.CharField(blank=True, default='No', max_length=10, null=True),
        ),
    ]
