# Generated by Django 5.2.9 on 2026-01-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0039_createuser_ismobile_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gslogin',
            name='status',
            field=models.CharField(default='Inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='tclogin',
            name='status',
            field=models.CharField(default='Inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='tllogin',
            name='status',
            field=models.CharField(default='Inactive', max_length=20),
        ),
    ]
