# Generated by Django 5.2.9 on 2026-01-15 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0040_alter_gslogin_status_alter_tclogin_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave_request',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField()),
                ('user_mobile', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=50)),
                ('leave_type', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('full_day_half', models.CharField(max_length=15)),
                ('leave_reason', models.TextField()),
                ('leave_desc', models.TextField()),
                ('leave_status', models.CharField(default='Pending', max_length=20)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kg_app.admin_user_model')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kg_app.createuser')),
            ],
        ),
    ]
