# Generated by Django 5.2.9 on 2026-02-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0042_create_task_tl_name_create_task_tl_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_task',
            name='tl_name',
        ),
        migrations.RemoveField(
            model_name='create_task',
            name='tl_userName',
        ),
    ]
