# Generated by Django 5.2.9 on 2026-02-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0043_remove_create_task_tl_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_task',
            name='tl_name',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='tl_userName',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
