# Generated by Django 5.2.9 on 2026-02-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0044_create_task_tl_name_create_task_tl_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_user_model',
            name='admin_system_id',
            field=models.CharField(blank=True, default='ADMIN-001', max_length=50, null=True),
        ),
    ]
