# Generated by Django 5.2.9 on 2026-02-26 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0045_admin_user_model_admin_system_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_task',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='create_task',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
