# Generated by Django 5.2.9 on 2026-02-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0046_create_task_submit_time_create_task_updated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_update',
            name='updated_by_role',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
    ]
