# Generated by Django 5.2.9 on 2026-02-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0047_task_update_updated_by_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_user_model',
            name='role',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
