# Generated by Django 5.2.9 on 2026-02-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0048_admin_user_model_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='login_status',
            field=models.CharField(blank=True, default='Inactive', max_length=10, null=True),
        ),
    ]
