# Generated by Django 5.2.9 on 2026-03-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0049_createuser_login_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_task',
            name='customer_mobile_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='role',
            field=models.CharField(choices=[('telecaller', 'Telecaller'), ('teamlead', 'Team Lead'), ('groundstaff', 'Ground Staff'), ('repoboy', 'Repro Boy')], max_length=20),
        ),
    ]
