# Generated by Django 5.2.9 on 2026-03-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0050_alter_create_task_customer_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_task',
            name='aggrement_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
