# Generated by Django 5.2.9 on 2026-03-11 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0051_alter_create_task_aggrement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='kg_app.createuser'),
        ),
        migrations.AddField(
            model_name='createuser',
            name='is_assignment_locked',
            field=models.BooleanField(default=False),
        ),
    ]
