# Generated by Django 5.2.9 on 2026-03-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0052_createuser_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_update',
            name='updated_by_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
