# Generated by Django 5.2.9 on 2026-03-20 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0053_task_update_updated_by_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_update',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kg_app.create_task'),
        ),
    ]
