# Generated by Django 5.2.9 on 2026-04-01 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0054_alter_task_update_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoLogin',
            fields=[
                ('gs_login_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('status', models.CharField(default='Inactive', max_length=20)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='repo_login/')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kg_app.createuser')),
            ],
        ),
    ]
