# Generated by Django 5.2.9 on 2026-04-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0056_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('category', models.CharField(blank=True, choices=[('Design', 'Design & UI'), ('Performance', 'Performance'), ('Features', 'Features'), ('Support', 'Support'), ('Pricing', 'Pricing'), ('Other', 'Other')], max_length=20)),
                ('message', models.TextField(blank=True, max_length=300)),
                ('nps_score', models.SmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
