# Generated by Django 5.2.9 on 2026-04-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0057_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback Submissions'},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_id',
            field=models.CharField(db_index=True, default='legacy_user', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
