# Generated by Django 5.2.9 on 2026-04-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0058_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_list',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
