# Generated by Django 5.1.3 on 2026-04-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0060_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_request',
            name='user_email',
            field=models.CharField(max_length=80),
        ),
    ]
