# Generated by Django 5.1.3 on 2026-04-16 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0061_alter_leave_request_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='track_repo_search_history',
            fields=[
                ('search_id', models.AutoField(primary_key=True, serialize=False)),
                ('search_query', models.CharField(max_length=255)),
                ('vehicle_registration_number', models.CharField(max_length=30)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_mobile_number', models.CharField(max_length=15)),
                ('search_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kg_app.createuser')),
            ],
        ),
    ]
