# Generated by Django 5.1.3 on 2026-04-16 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0062_track_repo_search_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='track_repo_search_history',
            name='admin_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kg_app.admin_user_model'),
        ),
    ]
