# Generated by Django 5.1.3 on 2026-04-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0063_track_repo_search_history_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
