# Generated by Django 5.1.3 on 2026-04-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0064_alter_feedback_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.TextField(blank=True),
        ),
    ]
