# Generated by Django 5.2.9 on 2026-04-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0065_alter_feedback_options_alter_feedback_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarqueeMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(help_text='Text to display in the marquee banner.')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to show or hide the marquee on the site.')),
                ('speed', models.PositiveIntegerField(default=40, help_text='Scroll speed in seconds (lower = faster).')),
                ('background_color', models.CharField(default='#5250c3', help_text='Background color (hex or CSS value).', max_length=20)),
                ('text_color', models.CharField(default='#ffffff', help_text='Text color (hex or CSS value).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marquee Message',
                'verbose_name_plural': 'Marquee Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
