# Generated by Django 5.2.9 on 2026-04-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0067_fcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmtoken',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
