# Generated by Django 5.2.9 on 2026-04-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0068_fcmtoken_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_task',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='create_task',
            name='engine_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
