# Generated by Django 5.2.9 on 2026-04-24 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0069_create_task_chassis_number_create_task_engine_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoTaskCreate',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('vehicle_registration_number', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=50)),
                ('engine_number', models.CharField(max_length=50)),
                ('chassis_number', models.CharField(max_length=50)),
                ('bucket', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=100)),
                ('collection_manager_name', models.CharField(max_length=100)),
                ('collection_manager_mobile_number', models.CharField(max_length=15)),
                ('finance_company_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kg_app.admin_user_model')),
            ],
        ),
    ]
