# Generated by Django 5.2.9 on 2026-04-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0070_repotaskcreate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repotaskcreate',
            old_name='task_id',
            new_name='repo_task_id',
        ),
    ]
