# Generated by Django 5.2.9 on 2026-04-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0071_rename_task_id_repotaskcreate_repo_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_user_model',
            name='canLogin',
            field=models.BooleanField(default=True),
        ),
    ]
