# Generated by Django 5.2.9 on 2026-05-07 08:09

import kg_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kg_app', '0072_admin_user_model_canlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_user_model',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='admin_user_model',
            name='valid_till',
            field=models.DateTimeField(default=kg_app.models.default_valid_till),
        ),
    ]
